import localFont from "next/font/local";
import "./style.scss";

export const metadata = {
    title: "Designjoy - Design as a Subscription",
    description: "Generated by create next app",
};

const brockmann = localFont({
    src: "./fonts/Brockmann.woff",
    variable: "--font-brockmann",
    weight: "100 900",
});

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${brockmann.variable}`}>
                {children}
            </body>
        </html>
    );
}
